title: 我的博客
description: 一个简洁的 GitHub Pages 博客
baseurl: "" 
url: "https://yourname.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/page:num/"
